export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_BY_GENRE = 'FETCH_MOVIES_BY_GENRE';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_GENRE = 'FETCH_GENRE';