export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_BY_GENRE = 'FETCH_MOVIES_BY_GENRE';
export const FETCH_GENRE = 'FETCH_GENRE';
export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_VIDEOS = 'FETCH_MOVIE_VIDEOS';